config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'

  resources :items, only: %i[index show]

  resources :carts, only: [:show]

  resources :orders, only: %i[create show index]

  post 'create_or_update', to: 'carts#create_or_update'

  # api routes
  namespace :api, defaults: { format: 'json' } do
    resources :items, only: [:index]
    resources :carts, only: %i[index create]
    resources :orders, only: %i[create update]
  end
  resources :orders, only: %i[create show index]
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
  has_many :items, through: :cart_items
end

app/models/cart_item.rb
# frozen_string_literal: true

class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item

  validate :item_available

  private

  def item_available
    errors.add(:cart, "#{item.id} not available!") unless item.available? && quantity <= item.available_quantity
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :items
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :category
  has_many :items_orders
  has_many :orders, through: :items_orders
  has_many :cart_items
  belongs_to :tax

  def item_tax
    tax&.value.to_i / 100.0
  end

  def item_discount(item_ids)
    offer = Offer.where(item_id: item_ids, discount_item_id: id).first
    return 0 unless offer.present?

    price * offer.percentage_discount / 100.0
  end

  def available?
    available_quantity.positive?
  end
end

app/models/items_order.rb
# frozen_string_literal: true

class ItemsOrder < ApplicationRecord
  belongs_to :item
  belongs_to :order

  after_commit :update_item_quantity

  validate :item_available

  private

  def item_available
    errors.add(:cart, "#{item.id} not available!") unless item.available? && ordered_quantity <= item.available_quantity
  end

  def update_item_quantity
    if saved_change_to_ordered_quantity?
      updated_quantity = item.available_quantity.to_i - (saved_change_to_ordered_quantity[1] - saved_change_to_ordered_quantity[0].to_i)
      item.update_attribute(:available_quantity, updated_quantity)
    end
  end
end

app/models/offer.rb
# frozen_string_literal: true

class Offer < ApplicationRecord
  belongs_to :item
  belongs_to :discount_item, foreign_key: 'discount_item_id', class_name: 'Item'
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  has_many :items_orders
  has_many :items, through: :items_orders
  belongs_to :user

  after_save :order_notification

  def order_notification
    if saved_change_to_status? && (saved_change_to_status[1] == 'paid')
      NotificationMailer.new_order_email(self).deliver_now
      NotificationSendJob.set(wait: 1.minutes).perform_later(id)
    end
  end
end

app/models/tax.rb
# frozen_string_literal: true

class Tax < ApplicationRecord
  has_many :items
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_one :cart
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def create_or_update
    CartService.new(cart_params, current_user).add_items
    redirect_to items_path
  end

  def show
    cart = Cart.find(params[:id])
    @cart_items = cart.cart_items
  end

  def cart_params
    permitted_params = { items: [] }
    permitted_params[:items] << params.permit(:item_id, :quantity).to_h
    permitted_params
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  def index
    @items = ItemService.new.items
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  def create
    order = OrderService.new(params, current_user).create
    if order[:data].present? && order[:data].id.present?
      redirect_to order_path(order[:data])
    else
      redirect_to items_path
    end
  end

  def index
    @orders = current_user.orders
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoffeeShop</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render "layouts/shared/header"%>
    <span class="notice"><%= notice %></span>
    <span class="alert"><%= alert %></span>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Coffee Shop</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% unless user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Sign In", "/users/sign_in", class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <%= link_to "Items", items_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Cart", cart_path(current_user.cart), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/orders">Orders</a>
        </li>
        <li class="nav-item">
          <%= link_to "Log Out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>