config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'home#index'

  resources :items, only: %i[index show]

  resources :carts, only: [:show]

  resources :orders, only: %i[create show index]

  post 'create_or_update', to: 'carts#create_or_update'

  # api routes
  namespace :api, defaults: { format: 'json' } do
    resources :items, only: [:index]
    resources :carts, only: %i[index create]
    resources :orders, only: %i[create update]
  end
  resources :orders, only: %i[create show index]
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
  has_many :items, through: :cart_items
end

app/models/cart_item.rb
# frozen_string_literal: true

class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item

  validate :item_available

  private

  def item_available
    errors.add(:cart, "#{item.id} not available!") unless item.available? && quantity <= item.available_quantity
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :items
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  belongs_to :category
  has_many :items_orders
  has_many :orders, through: :items_orders
  has_many :cart_items
  belongs_to :tax

  def item_tax
    tax&.value.to_i / 100.0
  end

  def item_discount(item_ids)
    offer = Offer.where(item_id: item_ids, discount_item_id: id).first
    return 0 unless offer.present?

    price * offer.percentage_discount / 100.0
  end

  def available?
    available_quantity.positive?
  end
end

app/models/items_order.rb
# frozen_string_literal: true

class ItemsOrder < ApplicationRecord
  belongs_to :item
  belongs_to :order

  after_commit :update_item_quantity

  validate :item_available

  private

  def item_available
    errors.add(:cart, "#{item.id} not available!") unless item.available? && ordered_quantity <= item.available_quantity
  end

  def update_item_quantity
    if saved_change_to_ordered_quantity?
      updated_quantity = item.available_quantity.to_i - (saved_change_to_ordered_quantity[1] - saved_change_to_ordered_quantity[0].to_i)
      item.update_attribute(:available_quantity, updated_quantity)
    end
  end
end

app/models/offer.rb
# frozen_string_literal: true

class Offer < ApplicationRecord
  belongs_to :item
  belongs_to :discount_item, foreign_key: 'discount_item_id', class_name: 'Item'
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  has_many :items_orders
  has_many :items, through: :items_orders
  belongs_to :user

  after_save :order_notification

  def order_notification
    if saved_change_to_status? && (saved_change_to_status[1] == 'paid')
      NotificationMailer.new_order_email(self).deliver_now
      NotificationSendJob.set(wait: 1.minutes).perform_later(id)
    end
  end
end

app/models/tax.rb
# frozen_string_literal: true

class Tax < ApplicationRecord
  has_many :items
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  has_one :cart
end

app/controllers/api/carts_controller.rb
# frozen_string_literal: true

module Api
  class CartsController < Api::ApplicationController
    def create
      render json: CartService.new(cart_params, current_user).add_items
    end

    def index
      user_cart = CartService.new(params, current_user)
      render json: { cart_items: user_cart.list_items, cart_total: user_cart.total_amount }
    end

    private

    def cart_params
      params.require(:cart).permit(items: %i[item_id quantity])
    end
  end
end

app/controllers/api/items_controller.rb
# frozen_string_literal: true

module Api
  class ItemsController < Api::ApplicationController
    def index
      render json: ItemService.new.items
    end
  end
end

app/controllers/api/orders_controller.rb
# frozen_string_literal: true

module Api
  class OrdersController < Api::ApplicationController
    before_action :find_order, only: [:update]

    def create
      order = OrderService.new(params, current_user).create
      render json: order[:data], status: order[:status]
    end

    def update
      render json: @order.update!(order_params)
    end

    private

    def order_params
      params.require(:order).permit(:status)
    end

    def find_order
      @order = Order.find params[:id]
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def create_or_update
    CartService.new(cart_params, current_user).add_items
    redirect_to items_path
  end

  def show
    cart = Cart.find(params[:id])
    @cart_items = cart.cart_items
  end

  def cart_params
    permitted_params = { items: [] }
    permitted_params[:items] << params.permit(:item_id, :quantity).to_h
    permitted_params
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  def index
    @items = ItemService.new.items
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  def create
    order = OrderService.new(params, current_user).create
    if order[:data].present? && order[:data].id.present?
      redirect_to order_path(order[:data])
    else
      redirect_to items_path
    end
  end

  def index
    @orders = current_user.orders
  end

  def show
    @order = Order.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/items_helper.rb
# frozen_string_literal: true

module ItemsHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
end

app/views/carts/show.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Quantity</th>
    </tr>
  </thead>
  <tbody>
	<% @cart_items.each_with_index do |cart_item, index| %>  	
	    <tr>
	      <th scope="row"><%= index + 1 %></th>
	      <td><%= cart_item.item.name %></td>
	      <td><%= cart_item.quantity %></td>
	    </tr>
	<% end %>
  </tbody>
</table>
<% if @cart_items.present? %>
	<%= button_to "Place order", orders_path%>
<% else %>
	No Items in Cart
<% end %>

app/views/items/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
      <th scope="col">Category</th>
      <th scope="col">Tax</th>
      <th scope="col">Detail</th>
    </tr>
  </thead>
  <tbody>
	<% @items.each_with_index do |item, index| %> 
	    <tr>
	      <th scope="row"><%= index + 1 %></th>
	      <td><%= item.name %></td>
	      <td><%= item.available_quantity %></td>
	      <td><%= item.price %></td>
	      <td><%= item.category_name %></td>
	      <td><%= item.tax_value.to_i %></td>
	      <td><%= link_to "Item Detail", item_path(item)%></td>
	    </tr>
	<% end %>
  </tbody>
</table>

app/views/items/show.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
      <th scope="col">Category</th>
      <th scope="col">Tax</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td><%= @item.name %></td>
      <td><%= @item.available_quantity %></td>
      <td><%= @item.price %></td>
      <td><%= @item.category&.name %></td>
      <td><%= @item.tax&.value.to_i %></td>
    </tr>
  </tbody>
</table>
<%= form_for @item, url: create_or_update_path, method: :post do |f| %>
  Quantity: <%= text_field_tag "quantity" %><br />
  <%= hidden_field_tag "item_id", @item.id %>
  <%= f.submit "Add to Cart" %>
<% end %>

app/views/orders/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Email</th>
      <th scope="col">Total</th>
      <th scope="col">Items</th>
      <th scope="col">Detail</th>
    </tr>
  </thead>
  <tbody>
	<% @orders.each_with_index do |order, index| %>  	
	    <tr>
	      <th scope="row"><%= index + 1 %></th>
	      <td><%= order.user.email %></td>
	      <td><%= order.order_total %></td>
	      <td><%= order.items.pluck('name')%></td>
	      <td><%= link_to "Order Detail", order_path(order)%></td>
	    </tr>
	<% end %>
  </tbody>
</table>

app/views/orders/show.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Email</th>
      <th scope="col">Total</th>
      <th scope="col">Items</th>
    </tr>
  </thead>
  <tbody>
	<tr>
      <th scope="row">1</th>
      <td><%= @order.user.email %></td>
      <td><%= @order.order_total %></td>
      <td><%= @order.items.pluck('name')%></td>
    </tr>
  </tbody>
</table>